name: api checking tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests set
        required: true
        type: choice
        default: simple
        options:
          - smoke
          - simple
          - regression
          - all
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run regression tests
